queries = [
    "Algorithm complexity",
    "Quantum computing",
    "Cryptography",
    "Distributed systems",
    "Natural language processing",
    "Computer vision",
    "Parallel computing",
    "Data mining",
    "Graph theory",
    "Blockchain technology",
    "Operating systems",
    "Software engineering",
    "Human-computer interaction",
    "Machine learning",
    "Artificial intelligence",
    "Database management systems",
    "Cloud computing",
    "Cybersecurity",
    "Internet of Things (IoT)",
    "Augmented reality",
    "Virtual reality",
    "Edge computing",
    "Neural networks",
    "Reinforcement learning",
    "Computer graphics",
    "Embedded systems",
    "Bioinformatics",
    "Quantum algorithms",
    "Formal verification",
    "Robotics",
    "Uncertainty",
    "Bayesian updating",
    "Certainty theory",
    "Fuzzy logic",
    "Deep learning architectures",
    "Transfer learning",
    "Generative adversarial networks (GANs)",
    "Self-supervised learning",
    "Explainable AI",
    "Natural language understanding",
    "Few-shot learning",
    "Meta-learning",
    "Bayesian neural networks",
    "Attention mechanisms",
    "Recurrent neural networks (RNNs)",
    "Convolutional neural networks (CNNs)",
    "Transformer models",
    "Reinforcement learning policies",
    "AI ethics and bias",
    "Graph neural networks (GNNs)",
    "Neural architecture search (NAS)",
    "Autonomous agents",
    "Causal inference in AI",
    "Zero-shot learning",
    "Language models fine-tuning",
    "Multi-modal learning",
    "Neural machine translation",
    "AI in healthcare",
    "Adversarial machine learning",
    "Sparse neural networks",
    "Federated learning",
    "Contrastive learning",
    "Neurosymbolic AI",
    "Temporal difference learning",
    "Bayesian inference",
    "Markov Chain Monte Carlo (MCMC)",
    "Non-parametric statistics",
    "Hierarchical models",
    "Multivariate analysis",
    "Time series analysis",
    "Survival analysis",
    "Hypothesis testing",
    "Linear regression models",
    "Generalized linear models (GLM)",
    "Bootstrap methods",
    "Random effects models",
    "Causal inference",
    "Experimental design",
    "Bayesian networks",
    "Maximum likelihood estimation (MLE)",
    "Bayesian hierarchical models",
    "Multilevel models",
    "Robust statistics",
    "Empirical Bayes methods",
    "Latent variable models",
    "Sufficient statistics",
    "Frequentist vs Bayesian approaches",
    "Stochastic processes",
    "Sample size determination",
    "Principal component analysis (PCA)",
    "Factor analysis",
    "Monte Carlo simulations",
    "Density estimation",
    "Expectation-Maximization (EM) algorithm",
]